rm(list=ls())

library(SPEI)
library(plyr)
library(reticulate)
library(ggplot2)

# break down the arguments from Rscript
args <- commandArgs(trailingOnly=TRUE)
slice = as.character(args[1])                   # slice = '01'
years_sim_1 = as.numeric(args[2])               # years_sim_1 = 4000 ; years_sim_2 = 6000
metric = as.character(args[3])                  # metric = 'pr'
continent = as.character(args[4])               # continent = 'euro'
scen = as.character(args[5])                    # scen = 'hist'
year_start = as.numeric(args[6])                # year_start = 1971
year_end = as.numeric(args[7])                  # year_end = 2000

# slice = '01' ; years_sim_1 = 4000 ; years_sim_2 = 6000 ; metric = 'pr' ; continent = 'euro' ;
# scen = 'hist'; year_start = 1971 ; year_end = 2000

# local file outputs from IMAGE (change for on wrfstore because of python's weird system imposed by reticulate below)
image_output_local = '/home/rmp15/data/IMAGE/CLaGARMi/euro_cordex_output/'
file.loc.pr.hist.obs   = paste0(image_output_local,metric,'/out_',slice,'_y',years_sim_1,'_',continent,'_hist_1971_2000_',metric,'_o.npy' )
file.loc.pr.hist.sim   = paste0(image_output_local,metric,'/out_',slice,'_y',years_sim_1,'_',continent,'_hist_1971_2000_',metric,'_s.npy' )
file.loc.pr.rcp45.2021 = paste0(image_output_local,metric,'/out_',slice,'_y',years_sim_1,'_',continent,'_rcp45_2021_2050_',metric,'_s.npy' )
file.loc.pr.rcp45.2071 = paste0(image_output_local,metric,'/out_',slice,'_y',years_sim_1,'_',continent,'_rcp45_2071_2100_',metric,'_s.npy' )
file.loc.pr.rcp85.2021 = paste0(image_output_local,metric,'/out_',slice,'_y',years_sim_1,'_',continent,'_rcp85_2021_2050_',metric,'_s.npy' )
file.loc.pr.rcp85.2071 = paste0(image_output_local,metric,'/out_',slice,'_y',years_sim_1,'_',continent,'_rcp85_2071_2100_',metric,'_s.npy' )

# to enable reading of numpy files in R
np = import("numpy")

print('loading precipitation files')

# load historical file and sim files
i=1 # to fix
pr.hist.obs = np$load(file.loc.pr.hist.obs)
site.hist.obs = pr.hist.obs[i,,] ; rm(pr.hist.obs)
pr.hist.sim = np$load(file.loc.pr.hist.sim)
site.hist.sim = pr.hist.sim[i,,] ; rm(pr.hist.sim)
pr.rcp45.2021 = np$load(file.loc.pr.rcp45.2021)
site.rcp45.2021 = pr.rcp45.2021[i,,] ; rm(pr.rcp45.2021)
pr.rcp45.2071 = np$load(file.loc.pr.rcp45.2071)
site.rcp45.2071 = pr.rcp45.2071[i,,] ; rm(pr.rcp45.2071)
pr.rcp85.2021 = np$load(file.loc.pr.rcp85.2021)
site.rcp85.2021 = pr.rcp85.2021[i,,] ; rm(pr.rcp85.2021)
pr.rcp85.2071 = np$load(file.loc.pr.rcp85.2071)
site.rcp85.2071 = pr.rcp85.2071[i,,] ; rm(pr.rcp85.2071)

# month and year data
year.seq = rep(1:30, each=365)
month.seq = c(rep(1,31),rep(2,28),rep(3,31),rep(4,30),rep(5,31),rep(6,30),rep(7,31),rep(8,31),rep(9,30),rep(10,31),rep(11,30),rep(12,31))

# function to create X month SPI, attached reference data onto the front of the dataset if not the original real historical dataset
# once working with one site, adapt sites to be multiple IDs which can
process_spi = function(scen,type,spi.length){

    dat = get(paste0('site.',scen,'.',type))

    # get number of years
    num.years = dim(dat)[1]

    dat.vector = as.vector(t(dat))

    # two different routes, one if data is original CORDEX data...
    if(type=='obs'){

        # dataframe of precipitation records
        dat.site = data.frame(year=year.seq,month=month.seq,precip=dat.vector)

    }
    # ...other choice is if data is generated by IMAGE
    if(type!='obs'){
        # month and year data
        year.seq.long = rep(31:(num.years+30), each=365)
        month.seq = c(rep(1,31),rep(2,28),rep(3,31),rep(4,30),rep(5,31),rep(6,30),rep(7,31),rep(8,31),rep(9,30),rep(10,31),rep(11,30),rep(12,31))

        # to add original data as reference for SPI calculation
        dat.vector.obs = as.vector(t(site.hist.obs))
        dat.vector.long = c(dat.vector.obs, dat.vector)
        year.seq.long = c(year.seq, year.seq.long)

        # dataframe of precipitation records
        dat.site = data.frame(year=year.seq.long,month=month.seq,precip=dat.vector.long)

    }

    # summarise precipitation by month
    dat.site.summarised = ddply(dat.site,.(year,month),summarise,precip=sum(precip))

    # convert to mm m-2 s-1 (currently in kg m-2 s-1) https://www.convertunits.com/from/kg/cm2/to/water+column+[millimeter]
    # scale factor is 10,000
    dat.site.summarised$precip = 10000 * dat.site.summarised$precip

    if(type=='obs'){
        # use SPEI program to calculate SPI
        dat.spi <- spi(dat.site.summarised[,'precip'], spi.length)
    }
    if(type!='obs'){
        dat.sp <- spi(dat.site.summarised[,'precip'], spi.length, ref.start=c(1,1), ref.end=c(30,12))

    }
    return(dat.spi)
}

# calculate spi for each scenario
spi_3.hist.obs = process_spi('hist','obs',3)
spi_3.hist.sim = process_spi('hist','sim',3)
spi_3.rcp45.2021 = process_spi('rcp45','2021',3)
spi_3.rcp45.2071 = process_spi('rcp45','2071',3)
spi_3.rcp85.2021 = process_spi('rcp85','2021',3)
spi_3.rcp85.2071 = process_spi('rcp85','2071',3)


# create histograms by month

create_hist = function(dat){
    dat.hist = data.frame(spi=dat$fitted,month=rep(c(1:12)))
    names(dat.hist) = c('spi','month')

    return(dat.hist)
}

dat.spi_3.hist.obs = create_hist(spi_3.hist.obs)
dat.spi_3.hist.sim = create_hist(spi_3.hist.sim)
dat.spi_3.rcp45.2021 = create_hist(spi_3.rcp45.2021)
dat.spi_3.rcp45.2071 = create_hist(spi_3.rcp45.2071)
dat.spi_3.rcp85.2021 = create_hist(spi_3.rcp85.2021)
dat.spi_3.rcp85.2071 = create_hist(spi_3.rcp85.2071)


# dat.spi_3.hist.obs = data.frame(spi=spi_3.hist.obs$fitted,month=rep(c(1:12)))
# dat.spi_3.future.sim = data.frame(spi=spi_3.future.sim$fitted,month=rep(c(1:12)))
# names(dat.spi_3.future.sim) = c('spi','month') ; names(dat.spi_3.hist.obs) = c('spi','month')

# pdf TO FIX LOCATION
pdf("~/git/IMAGE/spi_plot.pdf",paper='a4r',height=0,width=0)
ggplot() +
    geom_density(data=dat.spi_3.hist.obs, aes(x=spi),color='black') +
    geom_density(data=dat.spi_3.hist.sim, aes(x=spi),color='grey') +
    geom_density(data=dat.spi_3.rcp45.2021, aes(x=spi),color='yellow') +
    geom_density(data=dat.spi_3.rcp85.2021, aes(x=spi),color='orange') +
    geom_density(data=dat.spi_3.rcp45.2071, aes(x=spi),color='red') +
    geom_density(data=dat.spi_3.rcp85.2071, aes(x=spi),color='dark red') +
    facet_wrap(~month)
dev.off()

########################################
# BELOW IS LEGACY CODE GENEARLISED ABOVE
########################################

# 1.'REAL' HISTORICAL DATA

# # test take one site and calculate SPI as test
# site = pr.hist.obs[1,,]
# site.vector.obs = as.vector(t(site))
#
# # create dataframe with year, month, precipitation
#
# dat.site = data.frame(year=year.seq,month=month.seq,precip=site.vector.obs)
#
# # summarise precipitation by month
# dat.site.summarised = ddply(dat.site,.(year,month),summarise,precip=sum(precip))
#
# # convert to mm m-2 s-1 (currently in kg m-2 s-1) https://www.convertunits.com/from/kg/cm2/to/water+column+[millimeter]
# # scale factor is 10,000
# dat.site.summarised$precip = 10000 * dat.site.summarised$precip
#
# # ggplot(data=dat.site.summarised) + geom_line(aes(x=year,y=precip,group=month,color=month)) + facet_wrap(~month)
#
# # use SPEI program to calculate SPI
# spi_1.hist.obs <- spi(dat.site.summarised[,'precip'], 1)
# spi_3.hist.obs <- spi(dat.site.summarised[,'precip'], 3)
# spi_12.hist.obs <- spi(dat.site.summarised[,'precip'], 12)

# # 2. SIM DATA WITH FIXED REFERENCE PERIOD FOR PRESENT
# site = pr.hist.sim[1,,]
# site.vector.sim = as.vector(t(site))
#
# num.years = dim(site)[1]
#
# # create dataframe with year, month, precipitation
# year.seq.long = rep(31:(num.years+30), each=365)
# month.seq = c(rep(1,31),rep(2,28),rep(3,31),rep(4,30),rep(5,31),rep(6,30),rep(7,31),rep(8,31),rep(9,30),rep(10,31),rep(11,30),rep(12,31))
#
# year.seq.long = c(year.seq, year.seq.long)
# site.vector.long = c(site.vector.obs, site.vector.sim)
#
# dat.site = data.frame(year=year.seq.long,month=month.seq,precip=site.vector.long)
#
# # summarise precipitation by month
# dat.site.summarised = ddply(dat.site,.(year,month),summarise,precip=sum(precip))
#
# # convert to mm m-2 s-1 (currently in kg m-2 s-1) https://www.convertunits.com/from/kg/cm2/to/water+column+[millimeter]
# # scale factor is 10,000
# dat.site.summarised$precip = 10000 * dat.site.summarised$precip
#
# library(ggplot2)
# # ggplot(data=dat.site.summarised) + geom_line(aes(x=year,y=precip,group=month,color=month)) + facet_wrap(~month)
#
# # use SPEI program to calculate SPI
# spi_1.hist.sim <- spi(dat.site.summarised[,'precip'], 1, ref.start=c(1,1), ref.end=c(30,12))
# spi_3.hist.sim <- spi(dat.site.summarised[,'precip'], 3, ref.start=c(1,1), ref.end=c(30,12))
# spi_12.hist.sim <- spi(dat.site.summarised[,'precip'], 12, ref.start=c(1,1), ref.end=c(30,12))
#
# # 3. SIM DATA WITH FIXED REFERENCE PERIOD FOR FUTURE
# site = pr.sim.future[1,,]
# site.vector.sim.future = as.vector(t(site))
#
# num.years = dim(site)[1]
#
# # create dataframe with year, month, precipitation
# year.seq.long = rep(31:(num.years+30), each=365)
# month.seq = c(rep(1,31),rep(2,28),rep(3,31),rep(4,30),rep(5,31),rep(6,30),rep(7,31),rep(8,31),rep(9,30),rep(10,31),rep(11,30),rep(12,31))
#
# year.seq.long = c(year.seq, year.seq.long)
# site.vector.long = c(site.vector.obs, site.vector.sim.future)
#
# dat.site = data.frame(year=year.seq.long,month=month.seq,precip=site.vector.long)
#
# # summarise precipitation by month
# dat.site.summarised = ddply(dat.site,.(year,month),summarise,precip=sum(precip))
#
# # convert to mm m-2 s-1 (currently in kg m-2 s-1) https://www.convertunits.com/from/kg/cm2/to/water+column+[millimeter]
# # scale factor is 10,000
# dat.site.summarised$precip = 10000 * dat.site.summarised$precip
#
# library(ggplot2)
# # ggplot(data=dat.site.summarised) + geom_line(aes(x=year,y=precip,group=month,color=month)) + facet_wrap(~month)
#
# # use SPEI program to calculate SPI
# spi_1.future.sim <- spi(dat.site.summarised[,'precip'], 1, ref.start=c(1,1), ref.end=c(30,12))
# spi_3.future.sim <- spi(dat.site.summarised[,'precip'], 3, ref.start=c(1,1), ref.end=c(30,12))
# spi_12.future.sim <- spi(dat.site.summarised[,'precip'], 12, ref.start=c(1,1), ref.end=c(30,12))
